### ISSUE TITLE
[PSaaS Bug]: Uninstall does nothing in current version of PSaaS (2021.12.03)

### ISSUE THREAD

**Issue by BadgerOnABike** [PSaaS-Developers/Project_issues#10]
### Contact Details

brett.moore@nrcan-rncan.gc.ca

### What happened?

When I press uninstall it is instantly complete! However, it does nothing. See video

https://user-images.githubusercontent.com/10979751/153032479-a52beacb-b1df-4c27-8589-edc518b579e9.mp4

.

### Version

(Windows) 2021.12.xx

### What component are you seeing the problem on?

Builder, Manager, PSaaS Binary

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spydmobile** [comment]
@BadgerOnABike can you please test if this is fixed in last psaas please, if so, you can mark it closed.

**Comment by BadgerOnABike** [comment]
This is now working as of PSaaS 03.02

**Comment by BadgerOnABike** [comment]
Worth noting, the uninstaller was apparently still active when I shut down the PC 1.5 days later. Not sure if this is an internal issue or broader, would need another person to also test.

**Comment by spydmobile** [comment]
From Exec: @RobBryce Brett has windows 11 and can test with 2022-03-0X

**Comment by RobBryce** [comment]
@spydmobile - is this a stock build of Win11, or one specific to an agency?  And which edition of Win11?  I just upgraded my laptop to build 22H2, released a few weeks ago.

**Comment by spydmobile** [comment]
> @spydmobile - is this a stock build of Win11, or one specific to an agency? And which edition of Win11? I just upgraded my laptop to build 22H2, released a few weeks ago.

I did not open the ticket and dont have windows, @BadgerOnABike did, so perhpas he can comment....

**Comment by spydmobile** [comment]
@BadgerOnABike @RobBryce's Question to me on Oct 20 was meant for you.  Please Respond.

**Comment by BadgerOnABike** [comment]
Win 11 is my personal, nothing special going on. It continues to work today.

**Comment by BadgerOnABike** [comment]
Looking good on my Win 10 NRCan machine too as of 2022.03.02, apologies for the delays on this.
