### ISSUE TITLE
Prometheus: Cannot draw polygon weather patch

### ISSUE THREAD

**Issue by nealmcloughlin** [PSaaS-Developers/Project_issues#118]
Polygon weather patches can no longer be drawn on the map view of Prometheus version 2021.12.03. File imports work, but I can't manually draw a polygon.

**Comment by RobBryce** [comment]
I am not able to recreate this issue.
![image](https://user-images.githubusercontent.com/17237535/188539707-68b050e2-4322-4968-afa7-518814c6873f.png)

**Comment by nealmcloughlin** [comment]
This is really weird. I experienced this bug back in July will using version 2021.12.03. I just tried it again with the same version and the bug has mysteriously fixed itself. Of note, my REDapp install was working when I reported this bug. Now my REDapp install will not open. Anyways, I'll close this as I can no longer replicate it either.
