### ISSUE TITLE
Project Licensing

### ISSUE THREAD

**Issue by spydmobile** [PSaaS-Developers/Project_issues#127]
We are at a point where we need to establish licensing. We have been targeting [GNU Affero General Public License V3](https://www.gnu.org/licenses/agpl-3.0.en.html) and yet we have not committed. This needs to happen sooner rather than later, so lets get all the legitimate concerns and roadblocks on the table here so we can work around them and licence the project.

**Comment by nealmcloughlin** [comment]
I support moving ahead with a license decision. We've discussed licensing options many times and just need to make a decision at this point. This team has likely done more thought and research on software licensing than any fire management agency in Canada. We're not going to get any direction from CIFFC as I had hoped. There's also no perfect license option out there, so I worry about another circular discussion. I'd like us to focus on the "best" license option to move ahead as opposed to the "perfect" license option we can't seem to find. I can commit to GNU Affero GPL v3.

**Comment by BadgerOnABike** [comment]
I am also in favor of AGPL 3

**Comment by spydmobile** [comment]
Ok, we have all agreed to pursue AGPLv3. This ticket should now be about achieving that. Lets start talking roadblocks and complications, @RobBryce can you list out the challenges as you see them moving forward, including your concerns for impacts to Firecast. this should be laid out, but this is a public ticket so keep that in mind.

**Comment by RobBryce** [comment]
@spydmobile At this point in time, given my understanding of the AGPLv3 license, there should be no impact to FireCast.  Why?  None of the user interface acts directly with the WISE API's.  There are internal processes and libraries that run consistently and automatically, with no user intervention, that interact with the API's and with a database.
The few changes to WISE are reported and tracked here, so contributions are known _a _priori_, for review, and submission tracked here, not via a pull request from internal development.

**Comment by spydmobile** [comment]
> @spydmobile At this point in time, given my understanding of the AGPLv3 license, there should be no impact to FireCast. Why? None of the user interface acts directly with the WISE API's. There are internal processes and libraries that run consistently and automatically, with no user intervention, that interact with the API's and with a database. 

Agreed, the way I built many of the front ends I have made for the engine directly expose the UI using the JS API to the public facing internet triggering Novel Distribution and therefore virality of the licence and as a result requires my UI to be AGPLv3 while yours does not.

**Comment by spydmobile** [comment]
To further clarify, the public facing Firecast application does not use the engine at all, it does not use the API either, so there is no dependancy on the engine or its API, if WISE was removed from the server, the public facing Firecast application would operate normally.

**Comment by RobBryce** [comment]
Correct.
