### ISSUE TITLE
test

### ISSUE THREAD

**Issue by lizzydchappy** [PSaaS-Developers/Project_issues#140]

**Comment by spydmobile** [comment]
@lizzydchappy Your test worked. but a better approach is to use the templates ;-)

**Comment by spydmobile** [comment]
Where did you create this?

**Comment by lizzydchappy** [comment]
Sorry, I was testing the level of permissions I had with the Zenhub. As you can tell, I now have access. I still request communication with the WISE team.





Classification: Protected A

**Comment by spydmobile** [comment]
> Sorry, I was testing the level of permissions I had with the Zenhub. As you can tell, I now have access. I still request communication with the WISE team. 

Yay! Im glad you got it up and running. I will close this ticket then! we can carry on in PM on discord ;-)
