### ISSUE TITLE
[WISE Bug]: Intel Compiler Version 2022.2.0.955 Doesn't Work

### ISSUE THREAD

**Issue by BadgerOnABike** [PSaaS-Developers/Project_issues#142]
### Contact Details

brett.moore@nrcan-rncan.gc.ca

### What happened?

Went to install WISE, didn't have the correct intel compiler. Grabbed one api version w_dpcpp_cpp_runtime_p_2022.2.0.9553 off the site. That does not work, nor does the previous compiler.

Is this hard coded? If yes, can it not be hard coded? Right on their homepage they mention being free of lock-ins and this feels like a lock-in?

Windows 11
WISE Dev V 2022.03.02

### Version

(Windows) 2021.12.xx

### What component are you seeing the problem on?

WISE Binary

**Comment by spydmobile** [comment]
@RobBryce thoughts?

**Comment by RobBryce** [comment]
This is to be expected, and has been discussed in the past.  This is also why we keep a copy of the Intel redistributable available for people to download.  Every release of the Intel compiler has a different GUID.  We need to modify the installer to track every GUID that Intel has used for their releases, and we cannot future-proof this without providing people with a download of the Intel redistributable.

**Comment by spydmobile** [comment]
> This is to be expected, and has been discussed in the past. This is also why we keep a copy of the Intel redistributable available for people to download.

@RobBryce the "redistributable available for people to download" that we have on FGM.ca does not work on win 11. That is what @BadgerOnABike is saying. We need another compiler, NOT the one we preserved on the website. 

he is also suggesting that the latest version doesnt have vendor lockin, and therefore maybe we should build with that?????

**Comment by RobBryce** [comment]
I was able to install the one on FGM.ca on my Windows 11 machine.  That version is recognized by our installer, where-as the one you will download won't be recognized by the installer because it has a different GUID (which I have confirmed).

The choice to use the Intel compiler was driven by performance needs, and can be revisited for other CLANG-based compilers.  However, we cannot build the Windows target with solely the Microsoft compiler, we now need another compiler in addition to Microsoft's.

**Comment by spydmobile** [comment]
ok @RobBryce , I find it strange (disturbing) that you can install it and use the FGM.CA compiler archived, but that @BadgerOnABike cannot. Brett can you confirm that the [Compiler on FGM.CA](https://spyd.com/fgm.ca/libs/w_dpcpp_cpp_runtime_p_2021.3.0.3372.exe) cannot install yon your win 11?

**Comment by BadgerOnABike** [comment]
Confirmed, this was an issue of the older would not overwrite the newer.
