### ISSUE TITLE
[WISE FR]: Provide an appropriate JSON schema file for the fgmj format

### ISSUE THREAD

**Issue by jordan-evens** [PSaaS-Developers/Project_issues#204]
### What is needed?

There is a server JSON schema definition located at https://github.com/WISE-Developers/wise_docs/blob/main/wise_config/assets/ServerConfiguration.schema.json

I'm not sure if it exists already in one of the repos, but I can't find any such schema definition for the FGMJ format.

Please indicate where/what the FGMJ JSON schema is in the WISE Documentation repo, as well as making sure that each FGMJ properly references the schema that should be used to validate it.

### How will this improve the project or tool?

This will make it so that an FGMJ file can be created and/or validated with any standard JSON library.

### Approvals Process

- [ ] Testing For Issue
- [ ] Executive Approval
- [ ] Merge
- [ ] Provide Attribution

**Comment by spydmobile** [comment]
Hmm, dont think so, dont think the FGMJ format is ever exposed to code at the javascript level so no such schema would exist. The definition of the FGMJ file format is a function of Google Protobuf, so in all likelyhood what you are after is defined in the protobuf definitions, NOT in a JSON file. Im trying to find it for you now, BUT if you go looking for yourself, beware, in the code if you see `SPARCS_P` that is psaas/wise.

**Comment by jordan-evens** [comment]
I was always under the impression that the J in FGMJ was JSON. If it's not supposed to be a JSON file then it probably needs to be corrected wherever it's referenced as one. e.g.:
https://github.com/WISE-Developers/WISE_Application/blob/9612e2bc29c7c78080d5a30c79894480156ce0cd/WISE_CLI_HELP.md?plain=1#L8
https://github.com/WISE-Developers/WISE_Application/blob/9612e2bc29c7c78080d5a30c79894480156ce0cd/WISE/cpp/WISE_P.cpp#L193

It looks like it's either being defined as JSON or using a JSON parser for it, so hopefully it conforms to the JSON file format:
https://github.com/WISE-Developers/WISE_Application/blob/9612e2bc29c7c78080d5a30c79894480156ce0cd/WISE/cpp/Initialization.proto.cpp#L418-L419
https://github.com/WISE-Developers/WISE_Manager_Component/blob/a4848840fca3b2e37c28f58ee2237175a63f4988/WISE_Manager_Lib/src/main/java/ca/wise/rpc/RPCServer.java#L96-L98
https://github.com/WISE-Developers/WISE_Application/blob/9612e2bc29c7c78080d5a30c79894480156ce0cd/WISE_Project/cpp/CWFGMProject.proto.cpp#L236-L241

**Comment by spydmobile** [comment]
it IS json and is supposed to be json, its just not defined by a JSON schema, its defined by a protobuf Schema (Which might write out a json schema) but the source of truth of an FGMJ file is protobuf not JSON.

**Comment by spydmobile** [comment]
and i am still searching for it right now.....

**Comment by spydmobile** [comment]
whats the priority on this? I am under a deadline and am sidelining to find this....

**Comment by jordan-evens** [comment]
No rush, just making notes of things as I try to read through the repos.
Seems like it's probably this then?
https://github.com/WISE-Developers/WISE_Application/blob/9612e2bc29c7c78080d5a30c79894480156ce0cd/WISE_Project/proto/cwfgmProject.proto

**Comment by spydmobile** [comment]
hmm, i dont think so?? not sure???. Since the origins of the FGMJ file are in the builder application which writes the json file to disk, i suspect thats where it is, not in the main applicaiton. but it is likely shared in other places...

in here maybe:
https://github.com/search?q=org%3AWISE-Developers+proto3&type=code

**Comment by RobBryce** [comment]
@jordan-evens - the decision, some time ago, was to enforce adherence to the schema by having users use one of the API's, not directly create it.
The schema is public, but not to be used directly by some JSON library to generate the FGMJ.
Builder, and WISE, are using Google's Protobuf library which will generate "legal" JSON and Proto files in accordance with the schema.
It's fine to read and consume the generated JSON with external libraries, though, but Google's generator will (should) ensure that the generated file is valid w/r to the schema.  And so far that's proven to be true, given what we see from WISE when loading the file.
