### ISSUE TITLE
[WISE Bug]: 80004005: Internal E_FAIL Error - Please report this to the W.I.S.E. support team.

### ISSUE THREAD

**Issue by nikosuser** [PSaaS-Developers/Project_issues#206]
### Contact Details

nk1017@ic.ac.uk

### What happened?

I created a job via the js api and tried to run it through wise.exe. Usually this works but this time I got this error. Attaching job file below.

### Version

(Ubuntu 2020) v1.0.0-beta

### Relevant log output

```shell
(job file too long for github, will attach somehow later)
```

### Approvals Process

- [ ] Testing For Issue
- [ ] Executive Approval
- [ ] Merge

**Comment by nikosuser** [comment]
[job.fgmj.txt](https://github.com/user-attachments/files/18140432/job.fgmj.txt)

**Comment by spydmobile** [comment]
@nikosuser if the job zipped up is more than 25mb then you could try to zip up the job without inputs, attach it and then zip and add the inputs separately. we also need the inputs created by the job, the logs created when wise tried to run the job etc. basically everything in this particular jobs job folder.

**Comment by nikosuser** [comment]
[job_20241215120559288.zip](https://github.com/user-attachments/files/18141554/job_20241215120559288.zip)

Here is the whole thing

**Comment by spydmobile** [comment]
I see nothing wrong with the raster inputs, which from my records, is the only thing I have ever seen generate that error:
@BadgerOnABike once said to me:
`80004005: Internal E_FAIL Error - Please report this to the PrometheusCOM support team.
I had changed the DEM to tif to try and suck it in that way. It was not happy.`

so there was a raster mismatch, but I checked yours and there rasters matched perfectly. HOWVER, something tells me you should try and convert those rasters to geotifs and try again. and when i get a chance I will try running your job.

**Comment by spydmobile** [comment]
One last thought, you should also try running it without injecting the rasters into the FGMJ, there is an option for that to turn it on and off, it might be FGMJ version? im not sure at this point, but if you know that option, try turning it off when you run the model.

**Comment by nikosuser** [comment]
I found why this happened, during export the very first fuel value was decimal (i.e. 3.0 instead of 3). Removing the .0 made the issue go away.
