### ISSUE TITLE
[Psaas/Prometheus Bug]: statistics retrieval for an individual fire point vertex

### ISSUE THREAD

**Issue by RobBryce** [PSaaS-Developers/Project_issues#35]
### Contact Details

rbryce@heartlandsoftware.ca

### What happened?

The code is set up to return either a valid statistic value, or an error code.  Unfortunately, error code values are in the range of valid statistic values.  Modify the code to distinguish between error codes (return value) and statistics value (return as a var parameter) so an error code can't be mistaken for a valid statistics value.
Currently, this situation shouldn't actually occur because of the code that is retrieving stat's from an individual fire point vertex.  However, I want to make this change so that future development doesn't inadvertently create this situation, leading to an incredibly hard debugging session.

### Version

(Dev) 2021.xx.xx

### What version of Windows are you seeing the problem on?

Windows 10 64-bit

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spydmobile** [comment]
@RobBryce confirmed this is done
