### ISSUE TITLE
[PSaaS FR]: Critical Paths for Assets (Contribution from HSS)

### ISSUE THREAD

**Issue by spydmobile** [PSaaS-Developers/Project_issues#43]
### Contact Details

spydmobile@gmail.com

### What is needed?

we need to be able to output a geospatial file with the critical path of the fire through the fuels to the asset.

### How will this improve the project or tool?

this could become the primary target for mitigation/fuel modification or to identify the path at greatest risk to the Asset.

- [ ] Testing to be done by @BadgerOnABike

**Comment by BadgerOnABike** [comment]
- [ ] Testing to be done by @BadgerOnABike

**Comment by spydmobile** [comment]
@RobBryce confirmed this is done
