### ISSUE TITLE
[PSaaS Bug]: FGMB file save is broken

### ISSUE THREAD

**Issue by RobBryce** [PSaaS-Developers/Project_issues#48]
### Contact Details

rbryce@heartlandsoftware.ca

### What happened?

You can't save a FGMB file in Prometheus or PSaaS right now.

### Version

(Windows) 2021.12.xx

### What component are you seeing the problem on?

PSaaS Binary

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spydmobile** [comment]
@RobBryce confirmed this is done
