### ISSUE TITLE
[TASK] Develop a new website, combining fgm.ca and new directions and themes.

### ISSUE THREAD

**Issue by spydmobile** [PSaaS-Developers/Project_issues#55]
- [x] RIP the fgm.ca site
- [x] Develop a static version
- [x] add some sustainability (Eg shared headers etc)
- [x] add redapp #56 
- [ ] Incorporate feedback from Exec Team
- [ ] establish as new baseline
- [ ] Publish to fgm.com (Use CNAME pointers in GHP)
- [ ] test
- [ ] Publish to fgm.ca (Use CNAME pointers in GHP)

**Comment by spydmobile** [comment]
@lizzydchappy are you talking about the website or the program? I cant find any issues in the website.

**Comment by lizzydchappy** [comment]
The program. The website looks great!

**Comment by spydmobile** [comment]
> The program. The website looks great!

Ahhh, ok, when you notice a problem with a program, please go here and file a bug, thanks!!!
You can click ***NEW ISSUE*** top right of the page, or go [here](https://github.com/PSaaS-Developers/Project_issues/issues/new/choose):
