### ISSUE TITLE
[PSaaS FR]: Exporting scenario-specific fuel grids

### ISSUE THREAD

**Issue by RobBryce** [PSaaS-Developers/Project_issues#6]
### Contact Details

rbryce@heartlandsoftware.ca

### What is needed?

PSaaS (and Prometheus) allows the assignment of fuel patches (landscape and polygon) and even a new fuel grid entirely to a scenario.  This allows for scenario-specific modifications to a simulation to represent reality or create what-if studies on changing fuel types in part or all of the fuel grid area.

Prometheus allows the user to interactively export the fuel grid that the scenario actually uses (after application of all patches, etc.), so that this can be reviewed for accuracy and/or re-imported back into a GIS system.

PSaaS is missing this feature, and thus validation of fuel patches, etc. is hard to perform.

### How will this improve the project or tool?

This will aid in validation of PSaaS 7.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spydmobile** [comment]
@RobBryce confirmed this is done
