### ISSUE TITLE
[PSaaS Bug]: Geoserver communication

### ISSUE THREAD

**Issue by RobBryce** [PSaaS-Developers/Project_issues#67]
### Contact Details

rbryce@heartlandsoftware.ca

### What happened?

Item #46 covered work needed for PSaaS to interact with Geoserver to upload data.  Some required work in V6 was not merged into V7 when building 2021.03.01.  This was discovered upon initial deployment of PSaaS 7 Linux.

### Version

(Linux) 2021.11.xx

### What component are you seeing the problem on?

PSaaS Binary

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spydmobile** [comment]
@RobBryce confirmed this is done
