### ISSUE TITLE
[PSaaS Bug]: Sub-scenarios in V7

### ISSUE THREAD

**Issue by RobBryce** [PSaaS-Developers/Project_issues#68]
### Contact Details

rbryce@heartlandsoftware.ca

### What happened?

Some work to correctly handle sub-scenarios in was not properly migrated from V6 to V7.  Specifically, the initialization of sub-scenarios, done differently between v6 and v7, needed work.  This was discovered immediately when deploying PSaaS v7.

### Version

(Linux) 2021.11.xx

### What component are you seeing the problem on?

PSaaS Binary

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spydmobile** [comment]
@RobBryce confirmed this is done
