### ISSUE TITLE
[PSaaS Bug]: NUMA node issues

### ISSUE THREAD

**Issue by RobBryce** [PSaaS-Developers/Project_issues#81]
### Contact Details

rbryce@heartlandsoftware.ca

### What happened?

NUMA node and core assignment is important for PSaaS on large core machines.  If too many cores are used by PSaaS, then the process will slow down because it spends too much time synchronizing threads vs. running them.  NUMA locking is a performance issue.

In October, we discovered and fixed an issue with NUMA locking on Windows, thanks to Microsoft changing the API to this functionality.

Recent tests indicate similar issues on AMD server machines running Ubuntu 20.x.  It's unclear if it's the OS, HAL, or library we're using, but sometimes were are locked to NUMA node 0, other attempts lock to core 0 on the requested NUMA node.

More investigation is needed to correct core locking in Linux.

### Version

(Linux) 2021.11.xx

### What component are you seeing the problem on?

PSaaS Binary

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BadgerOnABike** [comment]
Notably, not even large core machines. Multiple physical CPU machines. The NUMA node only exists when there is more than 1 CPU.

**Comment by RobBryce** [comment]
We've only had problems on the OVH Advance-5.  One AMD Epyc 7413, but shows 4 NUMA nodes, running Ubuntu 20.x
No problem with a system with AMD 5950X (1 NUMA node), running the same OS.
It also worked for us on a Ubuntu VM hosted on Windows configured to match the Epyc 7413 (for testing purposes).
The Windows code works fine with single and multi-processor hardware configurations, though that doesn't contribute here, other than for breadth of follow-up testing that's needed here.

Every test we've done so far, the OS always reports at least 1 NUMA node.

**Comment by spydmobile** [comment]
this can be a time sync we should limit to 4 hours of billable time.

**Comment by RobBryce** [comment]
This work will proceed based on the expectation that the OS function calls that we are using are working correctly, and there's a problem with our understanding and/or assumptions around these calls, and of the hardware topology.  Plan is to research hardware a bit more, see if there are any forums we can query on, and experiment with additional calls to set core affinity to get some insight on the behaviour of these calls.

**Comment by spydmobile** [comment]
@RobBryce will test, and show resolved by adding screen caps
