### ISSUE TITLE
[PSaaS FR]: Refresh protobuf definitions

### ISSUE THREAD

**Issue by RobBryce** [PSaaS-Developers/Project_issues#88]
### Contact Details

rbryce@heartlandsoftware.ca

### What is needed?

During an early meeting with Jordan, myself, Franco, and others, we discussed a need to refresh the protobuf definition.  This clean-up would be a breaking change so ideally performed before any public release where we would need to consider backwards compatibility.  This item was captured in REDMine 1289 https://ppm.redapp.org/issues/1289.

### How will this improve the project or tool?

8 years of PSaaS development, and 3.5 years of protobuf definition refinement have led to some redundancy that is ideally resolved before the format is public.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spydmobile** [comment]
@RobBryce this just needs a rough time estimate, no real plan needed.

**Comment by RobBryce** [comment]
This needs review, I'll provide some suggested protobuf edits and we'll need approval on this plan, since it needs vetted by people with long-range planning here.

**Comment by RobBryce** [comment]
I'll suggest a following plan:

1. Provide a set of protobuf files, and with that a document for revisions (collapse of layers, remove redundancy).  That's what this initial quote is for.
2. Discussion as necessary to clarify what I want to do with the team, and also adjust based on team objectives.  Unknown duration, but it's discussion/meeting time.
3. Act based on the conclusion of that discussion.  Quote for this will come pending results of the prior step, and whether it's unique to WISE (V7 code base), or if Prometheus (V6 code base) will also be modified to handle the updates.

**Comment by RobBryce** [comment]
This revision is not minor.  We have a few options for dealing with various tools using these files.

1.) We update Prometheus/PSaaS V6 to match work being done in PSaaS/WISE V7 source tree.  This is the easiest path forward for users since it's convenient.  But it means more regression testing on both source trees.  And possible issues with bug fixes in an otherwise static Prometheus source tree.

2.) We update only the V7 source tree, and build in functionality into V7 to save the old vs. new FGMJ file formats.  This is easier for development because Prometheus does not change.  There is less regression testing too.  But it means another step for the user to consume the new file format in Prometheus.  Note that generating V1 of the file (old version) from V2 could be automated, it depends on how these files will be used.

**Comment by spydmobile** [comment]
Option 2 seem like the only sensible choice to me, especially if we want to release wise 1.0 this year.

**Comment by BadgerOnABike** [comment]
Option 2 makes sense for me as well. had a side chat with Franco to ensure my understanding was in the right place. This will be the most logical path ahead to ensure there is some sanity checking possible through the dev/testing team but does not impact Prometheus. As far as I'm concerned the Prometheus code is as it will be upon final release minus some cosmetic enhancements.

**Comment by RobBryce** [comment]
[proto.zip](https://github.com/PSaaS-Developers/Project_issues/files/8997568/proto.zip)
Let's see if this attachment works.  I've created two sub-folders - the current proto definitions for the FGMJ/FGMB files, and the revision.  Use WinMerge to see the changes.  In summary, we've collapsed 1 or 2 levels of abstraction in the files where possible to thus remove Prometheus-esque architecture details from the file format.  To maintain backwards compatibility, elements strictly for Prometheus (or some other visualization tool) continue to exist but as optional parameters.
To implement these changes, much of the code will need modified to point to a different structure that wraps the proto message.  It should go relatively smoothly because the elements still exist, just in another spot in the file.

**Comment by BadgerOnABike** [comment]
Everything in there makes sense to me. Seems to localize functionality back to the definition its actually relevant to the element its defining. However I'm not so well versed in this material that I would be able to say whether or not something is missing or needed to be included. From what I can see everything that was still is for the most part, many layers of deprecation to move away from the old way of doing things. Looks decent to me!
